// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIW01z5l7sfkN54IFVz96Aa-3N2tZerA',
    appId: '1:958323945763:web:0f7a6427a76b9f27189c96',
    messagingSenderId: '958323945763',
    projectId: 'wit-portfolio',
    authDomain: 'wit-portfolio.firebaseapp.com',
    storageBucket: 'wit-portfolio.firebasestorage.app',
    measurementId: 'G-T47C6CCHM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPe5NJ9KIT7IjtXkrvAr7tjnCCO4yZAU',
    appId: '1:958323945763:android:5fcc223e14505fb5189c96',
    messagingSenderId: '958323945763',
    projectId: 'wit-portfolio',
    storageBucket: 'wit-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwlY05865ezZSGn-ab9NV_XjI1bWlioo',
    appId: '1:958323945763:ios:a7efc38fa42c901e189c96',
    messagingSenderId: '958323945763',
    projectId: 'wit-portfolio',
    storageBucket: 'wit-portfolio.firebasestorage.app',
    iosBundleId: 'com.wit.witPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjwlY05865ezZSGn-ab9NV_XjI1bWlioo',
    appId: '1:958323945763:ios:175c2bdba819269d189c96',
    messagingSenderId: '958323945763',
    projectId: 'wit-portfolio',
    storageBucket: 'wit-portfolio.firebasestorage.app',
    iosBundleId: 'com.wit.wit-portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSIW01z5l7sfkN54IFVz96Aa-3N2tZerA',
    appId: '1:958323945763:web:46cd385144f68a4a189c96',
    messagingSenderId: '958323945763',
    projectId: 'wit-portfolio',
    authDomain: 'wit-portfolio.firebaseapp.com',
    storageBucket: 'wit-portfolio.firebasestorage.app',
    measurementId: 'G-FJQK8GFKCW',
  );
}
